version: "3"

services:
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: idream
      MYSQL_USER: idream
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mariadb-entry-point:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3307:3306"
    restart: always

  app:
    build:
      context: .
    environment:
      DEPLOYMENT_ENV: development
      XDEBUG_CONFIG: "remoPte_connect_back=1 remote_autostart=1 remote_enable=1 remote_host=docker.for.mac.localhost"
    volumes:
      - /tmp:/tmp
      - .:/var/www/html/
    links:
      - mariadb
      - viz
    ports:
      - "127.0.0.1:8080:80"
    restart: always

  viz:
    image: tylerbiggs/chemmd:27
    volumes:
      - ./sites/default/files/vizdata:/opt/isadream/data
    expose:
      - "5006"
    ports:
      - "127.0.0.1:5006:5006"
    restart: always

  # drush:
  #   image: drush/drush:8
  #   volumes:
  #     - ./:/var/www/html
  #   links:
  #     - app
  #     - mariadb
  #   command: drush cc all
